spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deforestation_news
    username: najafov
    password: root
    hikari:
      schema: public
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    defer-datasource-initialization: false
springdoc:
  swagger-ui:
    doc-expansion: none
    tags-sorter: alpha

security:
  jwt:
    base64-secret: eUlKUFpFUjJkdEVtNDg0UUR5UDAxNlRWSnlLVnZ0WkZtM0VzRzh6Y2ZQSmk5vOGRGdEdzSlk1clV1RDlvSVFuVGtLeE9QMm96aHBzdWZDbzE2M0dWN2VWZ2JRT014SllIOWRRaFdm
    authentication-token-expires-minutes: 5
  cors:
    origin: "*"
    method: "*"
app:
  jwt-authentication-token-expires-minutes: 240
  secret-key: 77397A244326462948404D635166546A576E5A7234753778214125442A472D4B

server:
  port: 8082

static:
  role:
    admin_id: 1